import os

# docker-compose.yml
dc = open('docker-compose.yml', 'w', encoding='utf-8')
dc.write('version: "3.9"\n\n')
dc.write('networks:\n  app-net:\n    driver: bridge\n\n')
dc.write('volumes:\n  postgres_data:\n  keycloak_data:\n  localstack_data:\n\n')
dc.write('services:\n\n')
dc.write('  # PostgreSQL 16: banco principal.\n')
dc.write('  # SKIP LOCKED e essencial para o outbox worker disputar registros\n')
dc.write('  # sem bloquear outros workers da mesma outbox.\n')
dc.write('  postgres:\n')
dc.write('    image: postgres:16-alpine\n')
dc.write('    container_name: betting_postgres\n')
dc.write('    restart: unless-stopped\n')
dc.write('    environment:\n')
dc.write('      POSTGRES_USER: betting_user\n')
dc.write('      POSTGRES_PASSWORD: betting_password\n')
dc.write('      POSTGRES_DB: betting_db\n')
dc.write('    ports:\n      - "5432:5432"\n')
dc.write('    volumes:\n      - postgres_data:/var/lib/postgresql/data\n')
dc.write('    networks:\n      - app-net\n')
dc.write('    healthcheck:\n')
dc.write('      test: ["CMD-SHELL", "pg_isready -U betting_user -d betting_db"]\n')
dc.write('      interval: 10s\n      timeout: 5s\n      retries: 5\n      start_period: 10s\n\n')
dc.write('  # Keycloak 25: IdP OAuth2/OIDC. client_credentials flow.\n')
dc.write('  # Realm importado automaticamente de scripts/keycloak-realm.json.\n')
dc.write('  keycloak:\n')
dc.write('    image: quay.io/keycloak/keycloak:25.0\n')
dc.write('    container_name: betting_keycloak\n')
dc.write('    restart: unless-stopped\n')
dc.write('    environment:\n')
dc.write('      KC_BOOTSTRAP_ADMIN_USERNAME: admin\n')
dc.write('      KC_BOOTSTRAP_ADMIN_PASSWORD: admin\n')
dc.write('      KC_DB: postgres\n')
dc.write('      KC_DB_URL: jdbc:postgresql://postgres:5432/betting_db\n')
dc.write('      KC_DB_USERNAME: betting_user\n')
dc.write('      KC_DB_PASSWORD: betting_password\n')
dc.write('      KC_DB_SCHEMA: keycloak\n')
dc.write('      KC_HTTP_ENABLED: "true"\n')
dc.write('      KC_HOSTNAME_STRICT: "false"\n')
dc.write('      KC_HOSTNAME_STRICT_HTTPS: "false"\n')
dc.write('    command: [start-dev, --import-realm]\n')
dc.write('    volumes:\n')
dc.write('      - ./scripts/keycloak-realm.json:/opt/keycloak/data/import/realm.json:ro\n')
dc.write('      - keycloak_data:/opt/keycloak/data\n')
dc.write('    ports:\n      - "8080:8080"\n')
dc.write('    networks:\n      - app-net\n')
dc.write('    depends_on:\n      postgres:\n        condition: service_healthy\n')
dc.write('    healthcheck:\n')
dc.write('      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health/ready"]\n')
dc.write('      interval: 30s\n      timeout: 10s\n      retries: 10\n      start_period: 60s\n\n')
dc.write('  # LocalStack 3.7: AWS SQS emulado.\n')
dc.write('  # Filas criadas via scripts/init-localstack.sh na inicializacao:\n')
dc.write('  #   wager-transactions.fifo, wager-transactions-dlq.fifo, wager-events.fifo\n')
dc.write('  localstack:\n')
dc.write('    image: localstack/localstack:3.7\n')
dc.write('    container_name: betting_localstack\n')
dc.write('    restart: unless-stopped\n')
dc.write('    environment:\n')
dc.write('      SERVICES: sqs\n')
dc.write('      DEFAULT_REGION: us-east-1\n')
dc.write('      PERSISTENCE: 1\n')
dc.write('      DISABLE_EVENTS: 1\n')
dc.write('    ports:\n      - "4566:4566"\n')
dc.write('    volumes:\n')
dc.write('      - localstack_data:/var/lib/localstack\n')
dc.write('      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-sqs.sh:ro\n')
dc.write('    networks:\n      - app-net\n')
dc.write('    healthcheck:\n')
dc.write('      test: ["CMD-SHELL", "awslocal sqs list-queues"]\n')
dc.write('      interval: 15s\n      timeout: 10s\n      retries: 10\n      start_period: 20s\n')
dc.close()
print('docker-compose.yml criado')
